services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true

  - type: web
    name: react-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
